### ISSUE TITLE
Windows oasys-xoppy running error from util/bin 

### ISSUE THREAD

**Issue by xianbo** [oasys-kit/oasys-installation-scripts#7]
When run WS or Tc, or anything that should be located in the util/bin, see the error message below (using WS as an example)
"No such file or directory: 'ws.out'"

The system output shows:
"Inside xoppy_calc_ws. 
Running command ''C:\Anaconda3\lib\site-packages\orangecontrib\xoppy\util/bin/win32/ws'' in directory: C:\Users\???\Oasys "

It seems the WS python is trying to run from the wrong directory. The correct directory is
"C:\Anaconda3\Lib\site-packages\orangecontrib\xoppy\util\bin\windows"

**Comment by srio** [comment]
I think the problem is the working directory. 

Which Windows are you using?
When Oasys started, which working directory was set? Try to change to another existing directory (You can do it from the "i" at the left bottom)

For me, with the default directory, runs correctly: 

Inside xoppy_calc_ws. 
Running command 'c:\miniconda3\lib\site-packages\orangecontrib\xoppy\util\bin\windows\ws.exe' in directory: C:\Users\srio\Oasys

**Comment by xianbo** [comment]
It is not the working directory problem. I put ??? just to hide my user account. 

I am using Windows 10, 64bit.

**Comment by srio** [comment]
Fixed
